
services:
  db:
    image: postgres:15
    container_name: server-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:${POSTGRES_DB_VOLUME}
    networks:
      - ${NETWORK_NAME}

  pgadmin:
    image: dpage/pgadmin4
    container_name: server-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - ${NETWORK_NAME}

  backend:
    build: ./backend
    container_name: server-backend
    ports:
      - "5000:5000"
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - db
    networks:
      - ${NETWORK_NAME}
    volumes:
      - ./backend/uploads/profile_Image:${IMAGES_PROFILE_VOLUME}

  nextjs:
    build: ./frontend
    container_name: server-nextjs
    depends_on:
      - backend
    ports:
      - "4000:4000"
    networks:
      - ${NETWORK_NAME}

  mongodb:
    image: mongo:latest
    container_name: server-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:${MONGO_VOLUME}
    networks:
      - ${NETWORK_NAME}

  iot-server:
    build: ./iot-server
    container_name: server-iot-server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=${MONGO_URL}
    networks:
      - ${NETWORK_NAME}

volumes:
  db_data:
  mongo-data:

networks:
  app-net:
    driver: bridge